<?php
/**
 * Страница "Список записей журнала аудита".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>List of audit log entries</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>The list displays all user actions.</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>Date.</b> Date and time of user action;</li>
        <li><b>User / IP address.</b> IP address of user action;</li>
        <li><b>User / ID.</b> The ID of the user who performed the action;</li>
        <li><b>User / User.</b> Login of the user who performed the action;</li>
        <li><b>User / Name.</b> The name of the user who performed the action;</li>
        <li><b>User / Permission.</b>Permission under which the user action was performed;</li>
        <li><b>Module / ID.</b> The identifier of the module that executed the user's request;</li>
        <li><b>Module / Name.</b> Name of the module that executed the user's request;</li>
        <li><b>Controller / Name.</b> The identifier of the controller that executed the user's request.;</li>
        <li><b>Controller / Action.</b> The controller action that fulfilled the user request;</li>
        <li><b>Controller / Event.</b> The event of the controller that fulfilled the user's request;</li>
        <li><b>Controller / ID.</b> The identifier of the controller action or record on which the action was performed;</li>
        <li><b>Request / OS.</b> The name and version of the operating system of the user who performed the action;</li>
        <li><b>Request / Browser.</b> The name and version of the browser of the user who performed the action;</li>
        <li><b>Request / Route.</b> Route obtained from user request;</li>
        <li><b>Request / Method.</b> Method obtained from user request;</li>
        <li><b>Request / Code.</b> The response code returned to the user as a result of his request;</li>
        <li><b>Success.</b> The code determines whether the user has successfully completed the request.</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Clear.</b> Deletes all audit records;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Edit.</b> Show a form for viewing detailed information about an audit record.;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Select.</b> Selects or deselects audit records;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Refresh.</b> Refresh the list of audit records;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Record profiling.</b> Expands and collapses the Navigation Bar to display information for the selected audit record;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Show.</b> Shows hidden columns;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Help.</b> Shows the help window for the current list.;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Search.</b> Shows the form for searching records in the list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Filter.</b> Shows the form for filtering records in a list.</li>
    </ul>
</article>